#
# Copyright (C) 2015  Rudolf Tammekivi
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This file is generated by device/huawei/g620s/setup-makefiles.sh

PRODUCT_COPY_FILES += \
	vendor/huawei/g620s/proprietary/recovery/root/sbin/vm_bms:recovery/root/sbin/vm_bms \
	vendor/huawei/g620s/proprietary/system/bin/rmt_storage:system/bin/rmt_storage \
	vendor/huawei/g620s/proprietary/system/bin/libqmi_oem_main:system/bin/libqmi_oem_main \
	vendor/huawei/g620s/proprietary/system/bin/rmt_oeminfo:system/bin/rmt_oeminfo \
	vendor/huawei/g620s/proprietary/system/bin/test_diag:system/bin/test_diag \
	vendor/huawei/g620s/proprietary/system/bin/oeminfo_server:system/bin/oeminfo_server \
	vendor/huawei/g620s/proprietary/system/bin/oem_sar_main:system/bin/oem_sar_main \
	vendor/huawei/g620s/proprietary/system/bin/callife:system/bin/callife \
	vendor/huawei/g620s/proprietary/system/lib/liboeminfo.so:system/lib/liboeminfo.so \
	vendor/huawei/g620s/proprietary/system/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
	vendor/huawei/g620s/proprietary/system/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
	vendor/huawei/g620s/proprietary/system/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
	vendor/huawei/g620s/proprietary/system/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
	vendor/huawei/g620s/proprietary/system/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
	vendor/huawei/g620s/proprietary/system/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
	vendor/huawei/g620s/proprietary/system/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
	vendor/huawei/g620s/proprietary/system/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
	vendor/huawei/g620s/proprietary/system/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
	vendor/huawei/g620s/proprietary/system/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
	vendor/huawei/g620s/proprietary/system/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
	vendor/huawei/g620s/proprietary/system/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
	vendor/huawei/g620s/proprietary/system/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
	vendor/huawei/g620s/proprietary/system/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
	vendor/huawei/g620s/proprietary/system/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
	vendor/huawei/g620s/proprietary/system/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
	vendor/huawei/g620s/proprietary/system/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
	vendor/huawei/g620s/proprietary/system/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
	vendor/huawei/g620s/proprietary/system/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
	vendor/huawei/g620s/proprietary/system/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw
